eibex/reaction-light

bot.py

Message warning if the user is not an admin was actually
never sent due to a wrong indentation.

[FIX] "Not admin" warning on embed edit.

---

bot.py
setup.py

Read version from local .version file instead of modifying the current version strings on the different files.

read version from local .version file

---

bot.py

Catches errors/prevents tracebacks when:
- The bot tries to send an embed message to a channel where he
doesn't have the proper permissions.
- The bot tries to react to an embed message in a channel where he
doesn't have the proper permissions.

[IMP] Permission error handling.

---

bot.py

If the users have hidden the embed messages in their settings,they only see the reactions attached to an empty message.
This commit aims to make the embed messages 'optionnal' and rely on a normal message. Here's the changes on the commands:
**{prefix}new - message formatting (`step == 3`) :**
- `some text`:  Set only a message
- `some text // some embed title`:  Set a message with an embed that only has a title
- `some text // some embed title // some embed content`:  Set a message with an embed that has a title and some contents
**{prefix}edit:**
- `{prefix}edit #channelname // MESSAGE_NUMBER // New Message`:  Change the message's body
- `{prefix}edit #channelname // MESSAGE_NUMBER // New Message // New Embed Title (Optionnal)`: 
- If the reaction-role message already had an embed, it …

[IMP] Make `embeds` optionnal as those can be hidden clientside

---

bot.py

`none` can be used as a bot command argument. What it changes:
**new**
- Allow creating role-reaction messages with only an embed message (introduced by #21)
**edit**
- Allow editing/removing individually the message body, the embed's title and the embed's description

[IMP] Better versality for `new` and `edit` commands

---

.gitignore
rldb.py

Using python formatting to build SQL instructions is very insecure.
Also added .db files in `.gitignore`

[IMP] Prevent SQL Injections

---

README.md
bot.py
config.ini.sample
setup.py

* Adds configurable embed colours
* Adds command to edit them
* Adds config.ini entry (hexadecimal value)
Fixes #25 
Future enhancements should include a dict to translate "red", "yellow", ... into their hexadecimal counterparts.

Add configurable embed colours

---

.gitignore
CHANGELOG.md
README.md
bot.py
core/__init__.py
core/database.py
core/migration.py
core/schema.py

In the PR schema.py is added to handle database updates regardless of which version the user is updating from.
Still have to create a way to fill in the new column in the messages table and the remaining discord commands and logic to add system channels.
Will close #39

Better system channels and database updates

---

bot.py

Keep the embed footer after editing an reaction-light message, currently it removes the footer with this it simply keeps/updates the embed footer.
This PR simply add necessary code to re-add the embed footer instead of forgetting about it.

Keep the embed footer after editing an embed

---

bot.py
core/database.py

Fixes #52 by deleting a guilds database entries after leaving the guild / if the guild gets deleted.
In order to do this I added another database function (remove_guild) which just removes everything directly connected to the guild (message, reactionroles, systemchannels). **Please note**: This will NOT remove the admin role id from the database as admins table does not refer to which guild the admin role belongs to.

Re-work message clean up, re-work of the admin system and cleaning up left guilds

---

bot.py
core/database.py
core/schema.py

- Adds a new table called `guild_settings`: I would like to use this for anything guild related in the future, I tried to merge systemchannels into this but I couldn't find an elegant way yet. I will figure it out before merging... Most likely going to copy the contents into a new column and then delete the old table in the `one_to_two` function
- Moved the admin migration introduced by @Edwinexd from core.database to core.schema (I believe everything should still be working correctly)
- Adds a toggle command `rl!notify`
- Guilds are inserted into the table when either `rl!notify` is first used or when the bot checks for it (a user adds or removes a reaction from themselves). In the first case, the bot toggles the notification on, in the latter, the bot sets …

add notification toggles and checks

---

bot.py
core/schema.py

Changed the variable names in wait_for, fixed the issue you mentioned by adding locks and fixed two_to_three (you had written unique instead of limit_to_one, unique should never be in that list if I've understood the changes correctly. Ran in to an issue when running a test)

Variables, added locks & fixed two_to_three

---

bot.py

F-strings don't like other strings within their formatting ex: `string_a = f"Result: {f(1)}"` = Ok, `string_b = f"Result: {g("1")}"` = Syntaxerror
This PR simply re-does it with variables instead to prevent the syntaxerrors.
Mention any issues that this PR would close.
Closes #68

Fix f-string syntax errors

---

requirements.txt

**What was fixed:**
The "package" name for discord.py is discord.py not discord.
**Why the error occurred:**
PyCharm can't handle that discord.py is importing discord instead of discord.py.
That's why PyCharm creates a requirements.txt with discord instead of discord.py.
**Error that occurs with wrong requirements.txt:**
`ERROR: Could not find a version that satisfies the requirement discord>=1.6.0`
`ERROR: No matching distribution found for discord>=1.6.0`

Corrected requirements.txt

---

README.md

F-strings, which are used all around the bot weren’t introduced before python 3.6. This PR simply updates the readme to bump the minimum python version to run the bot to python 3.6.

Bump required python version

---

bot.py
core/database.py

Stops the bot from nuking the wrong DB entries during cleanup
Mention any issues that this PR would close.
Closes #73

Fix database deleting wrong DB entries

---

bot.py

Use of https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.close (`await bot.close()`) to gracefully shut down the bot and close all connections instead of `sys.exit()`

Gracefuller shutdowns/restarts

---

cogs/message.py

Changes the RL-New check to only wait for messages in the same channel as the command was executed in (as discussed in the discord server)
Mention any issues that this PR would close.

Only listen for messages in one channel

---

Dockerfile

This makes the output more useful by removing any buffering. Otherwise messages can be delayed, stuck in the buffer.
```
-u     Force the stdout and stderr streams to be unbuffered.  This option has no effect on the stdin stream.
```

Use unbuffered python output with Docker

---

cogs/admin.py
cogs/control.py
cogs/errors.py
cogs/help.py
cogs/message.py
cogs/settings.py
i18n/en-gb.json
tests/language_structure.json

Add guild_only checks & error messages for when guild-only commands such as /message new are ran in a non-guild context. 
Mention any issues that this PR would close.
Closes #131

Send error when a guild-only command is being ran in DMs
